# Generated by Django 4.0.5 on 2023-03-29 10:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_code', models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(999)])),
                ('country_code', models.CharField(max_length=2, unique=True)),
                ('country_name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='alteiadata',
            name='country_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.country'),
        ),
        migrations.AddField(
            model_name='beninyield',
            name='country_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.country'),
        ),
        migrations.AddField(
            model_name='communesatellite',
            name='country_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.country'),
        ),
        migrations.AddField(
            model_name='deptsatellite',
            name='country_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.country'),
        ),
        migrations.AddField(
            model_name='mothertree',
            name='country_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.country'),
        ),
        migrations.AddField(
            model_name='nursery',
            name='country_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.country'),
        ),
        migrations.AddField(
            model_name='nurseryplantshistory',
            name='country_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.country'),
        ),
        migrations.AddField(
            model_name='plantation',
            name='country_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.country'),
        ),
        migrations.AddField(
            model_name='specialtuple',
            name='country_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.country'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='country_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.country'),
        ),
        migrations.AddField(
            model_name='training',
            name='country_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.country'),
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='country_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.country'),
        ),
    ]
