# Generated by Django 4.0.5 on 2023-03-29 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_country_alteiadata_country_id_beninyield_country_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='phone_code',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(999)]),
        ),
    ]
