# Generated by Django 4.0.5 on 2023-05-04 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_country_latitude_country_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='phone_code',
        ),
    ]
