# Generated by Django 4.0.5 on 2023-05-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_country_phone_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_level', models.CharField(max_length=200)),
                ('second_level', models.CharField(max_length=200)),
                ('third_level', models.CharField(max_length=200)),
                ('fourth_level', models.CharField(max_length=200)),
                ('fifth_level', models.CharField(max_length=200)),
            ],
        ),
    ]
