# Generated by Django 4.0.5 on 2023-05-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_administrativelevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=0),
        ),
    ]
