# Generated by Django 4.2.1 on 2023-07-17 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_country_level0_field_country_level0_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beninyield',
            name='district',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='DistrictSatellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('commune', models.CharField(max_length=200, unique=True)),
                ('district', models.CharField(max_length=200, unique=True)),
                ('cashew_tree_cover', models.FloatField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('country_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.country')),
            ],
        ),
    ]
