# Generated by Django 4.0.5 on 2023-11-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_dataset_layer'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='arrondissement',
            field=models.CharField(default='', max_length=200),
        ),
    ]
