# Generated by Django 4.0.5 on 2024-04-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_trainer_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mothertree',
            name='owner_gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default='others', max_length=6),
        ),
        migrations.AlterField(
            model_name='plantation',
            name='altitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantation',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantation',
            name='owner_gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default='others', max_length=6),
        ),
    ]
