# Generated by Django 4.0.5 on 2024-04-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_mothertree_owner_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beninyield',
            name='altitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
