# Generated by Django 4.0.5 on 2024-07-30 10:22

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0015_alter_beninyield_altitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='GAUL1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('display', models.CharField(max_length=200)),
                ('size', models.FloatField()),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GAUL2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('display', models.CharField(max_length=200)),
                ('size', models.FloatField()),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('GAUL1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.gaul1')),
            ],
        ),
        migrations.CreateModel(
            name='GAUL3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('display', models.CharField(max_length=200)),
                ('size', models.FloatField()),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('GAUL1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.gaul1')),
                ('GAUL2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.gaul2')),
            ],
        ),
        migrations.CreateModel(
            name='ProtectedArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('orig_name', models.CharField(max_length=300)),
                ('designation', models.CharField(max_length=200)),
                ('designation_type', models.CharField(max_length=200)),
                ('area', models.FloatField()),
                ('rep_area', models.FloatField(blank=True, null=True)),
                ('gov_type', models.CharField(blank=True, max_length=200, null=True)),
                ('own_type', models.CharField(blank=True, max_length=200, null=True)),
                ('mang_auth', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(max_length=200)),
                ('status_yr', models.IntegerField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AdministrativeLevel',
        ),
        migrations.RemoveField(
            model_name='country',
            name='level0_field',
        ),
        migrations.RemoveField(
            model_name='country',
            name='level1_field',
        ),
        migrations.RemoveField(
            model_name='country',
            name='level2_field',
        ),
        migrations.RemoveField(
            model_name='country',
            name='level3_field',
        ),
        migrations.AddField(
            model_name='country',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='country_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='country',
            name='geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='country',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='country_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plantation',
            name='geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='protectedarea',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.country'),
        ),
        migrations.AddField(
            model_name='protectedarea',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='protected_areas_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='protectedarea',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='protected_areas_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gaul3',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.country'),
        ),
        migrations.AddField(
            model_name='gaul3',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gaul3_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gaul3',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gaul3_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gaul2',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.country'),
        ),
        migrations.AddField(
            model_name='gaul2',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gaul2_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gaul2',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gaul2_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gaul1',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.country'),
        ),
        migrations.AddField(
            model_name='gaul1',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gaul1_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gaul1',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gaul1_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
