# Generated by Django 4.0.5 on 2024-07-31 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_gaul1_gaul2_gaul3_protectedarea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantation',
            name='shape_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='plantation',
            name='arrondissement',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plantation',
            name='commune',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plantation',
            name='current_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantation',
            name='department',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plantation',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantation',
            name='owner_first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plantation',
            name='owner_last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plantation',
            name='village',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
