# Generated by Django 4.0.5 on 2023-05-19 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_administrativelevel'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remorganization',
            name='country_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.country'),
        ),
        migrations.AlterField(
            model_name='remorganization',
            name='domain',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
