# Generated by Django 4.0.5 on 2023-05-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_remorganization_country_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remuser',
            name='sended_request',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
