# Generated by Django 4.0.5 on 2023-06-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remuser_sended_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
