# Generated by Django 4.0.5 on 2023-06-21 14:38

import apps.authentication.models
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_remuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remuser',
            name='email',
        ),
        migrations.AddField(
            model_name='remrole',
            name='organization',
            field=models.ForeignKey(default=apps.authentication.models.get_default_user_org, on_delete=django.db.models.deletion.CASCADE, to='authentication.remorganization'),
        ),
        migrations.AlterField(
            model_name='remuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=17, region=None),
        ),
    ]
