# Generated by Django 4.2.2 on 2023-07-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_remuser_email_remrole_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remrole',
            name='role_name',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TNS-ADMIN', 'Tns-Admin'), ('TNS-STAFF', 'Tns-Staff'), ('GOV-ADMIN', 'Gov-Admin'), ('GOV-STAFF', 'Gov-Staff'), ('OTHER', 'Other')], default='OTHER', max_length=200),
        ),
    ]
